name: PR

'on':
  pull_request:
    branches:
      - main

concurrency:
  group: '${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  lint-and-validate:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Node dependencies
        run: make build
      - name: Lint JS/JSON files
        run: make lint
      - name: Validate JSON schemas
        if: always()
        run: make validate-schemas

